# Generated by Django 5.2.1 on 2025-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoRequestsHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=6, verbose_name='Request Method')),
                ('request_path', models.CharField(max_length=1024, verbose_name='Request Path')),
                ('request_data_text', models.TextField(blank=True, verbose_name='Request Data Text')),
                ('request_data_binary', models.BinaryField(blank=True, verbose_name='Request Data Binary')),
                ('request_content_type', models.TextField(default='application/json', verbose_name='Request Content Type')),
                ('requester_useragent', models.CharField(db_index=True, max_length=255, verbose_name='User Agent')),
                ('requester_ip', models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP Address')),
                ('requester_username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Username')),
                ('response_code', models.IntegerField(null=True, verbose_name='Response code')),
                ('response_data_text', models.TextField(blank=True, verbose_name='Response data Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Label')),
            ],
        ),
    ]
